version: "3.0"

services:
  gateway:
    image: traefik:v2.11.21
    ports:
      - "80:80"
      - "443:443"
      - "9090:8080"
    environment:
      - CF_DNS_API_TOKEN=<TO_BE_REPLACE>
      # - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./configs:/etc/traefik" 
      - "./certs/:/var/traefik/certs/:rw"
    networks:
      - apicilia_net
  
  whoami:
    image: traefik/whoami
    container_name: whoami-app
    networks:
      - apicilia_net

networks:
  apicilia_net:
    external: true