http:
  routers:    
    whoami-router:
      entryPoints: 
        - websecure
      rule: "Host(`api.ildevertapps.com`)"
      service: whoami-service
      tls: 
        certResolver: cloudflare

    keycloak-router:
      entryPoints: 
        - websecure
      rule: "Host(`keycloak.ildevertapps.com`)"
      service: keycloak-service
      tls: 
        certResolver: cloudflare

  # Declaring services
  services:
    whoami-service:
      loadBalancer:
        servers:
          - url: http://email:8025
          
    keycloak-service:
      loadBalancer:
        servers:
          - url: http://keycloak:8080
