
api:
  insecure: true
log:
  level: INFO
providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

experimental:

  plugins:
    
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.34"

    headauth:
      moduleName: "github.com/poloyacero/headauth"
      version: "v0.0.1"

  
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# -- Configure your CertificateResolver here...
certificatesResolvers:
  cloudflare:
    acme:
      email: ildevertdaisy@gmail.com  # <-- Change this to your email
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare  # <-- (Optional) Change this to your DNS provider
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
